### ISSUE TITLE
display only me

### ISSUE THREAD

**Issue by ravalus** [Venutius/bp-greeting-message#1]
Hello,
Is it possible that the welcome message is displayed only in the user's logged-in profile and disappears after passing and visiting another user's profile?

**Comment by Venutius** [comment]
Hi there, so you only want to see the message in the users own profile and not when they visit someone elses?

**Comment by Venutius** [comment]
Ok I've updated it, you'll need to reinstall it, let me know what you think. Now it should only display when the user visits their own profile.

**Comment by ravalus** [comment]
Unfortunately it does not work. It is still visible when I visit my friends' profile

**Comment by Venutius** [comment]
That should not be possible with the new code, as a test could you go to your own profile>>view and let me know if you can see the message once or twice?

**Comment by ravalus** [comment]
You're right, It works. I had, however, set as "Before the Activity Posting Form" instead of "Before User Profile information"
Would you be kind enough to introduce such a modification also for "Before the Activity Posting Form"?

**Comment by Venutius** [comment]
The other two settings display the message in three places: The Group activity page, in the sitewide activity page and in the users activity page. I've made an adjustment so that it will only display when the user is viewing their own activity. There's nothing I can do about the group or sitewide activity page as there's no displayed user to check against.
